version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
  jenkins-slave:
    container_name: jenkins-slave
    image: jenkins/jnlp-slave
    depends_on:
      - jenkins
    environment:
      - JENKINS_URL=http://jenkins:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins-data:
  